const constantDataType = {
  LOAD_QUIZES: 'LOAD_QUIZES',
  REGISTER: 'REGISTER',
  ADD_ADMIN: 'ADD_ADMIN',
  UPDATE_ADMIN: 'UPDATE_ADMIN',
  SAVE_QUIZES: 'SAVE_QUIZES',
  UPDATE_QUIZ: 'UPDATE_QUIZ',
  LOAD_QUIZES_DB: 'LOAD_QUIZES_DB',
  SAVE_RESULT: 'SAVE_RESULT',
  SAVE_RESULT_QUIZ: 'SAVE_RESULT_QUIZ',
  LOAD_INTI_QUIZES: 'LOAD_INTI_QUIZES',
  LOAD_ALL_RESULT: 'LOAD_ALL_RESULT',
};

export default constantDataType;
